id: P004432
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-17 11:21:08.582346
source_metadata:
  id: bdr:W3CN4816
  title: ཊཱིཀ་ཆེན་དགོངས་པ་རབ་གསལ།
  author: ''
  volumes:
    bf9f12209bab4a7691bc4fdc48598182:
      image_group_id: I3CN4818
      title: ''
      volume_number: 1
      total_pages: 626
      base_file: v001.txt
    b9fc352d5c7c486a966c09e8d56605d4:
      image_group_id: I3CN4819
      title: ''
      volume_number: 2
      total_pages: 0
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
