id: I2321C727
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T01:40:24+00:00'
last_modified: '2022-06-08T00:58:51.243993+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN4816
  title: ཊཱིཀ་ཆེན་དགོངས་པ་རབ་གསལ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    C1DD:
      image_group_id: I3CN4818
      title: ''
      total_pages: 626
      order: 1
      base_file: C1DD.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
